server:
  port: 8085
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.105:3306/guli_sms
    username: root
    password: root
  redis:
    host: 192.168.1.105
mybatis-plus:
  global-config:
    db-config:
      id-type: auto #主键类型 AUTO:“数据库ID自增”, INPUT:“用户输入ID”, ID_WORKER:“全局唯一ID (数字类型唯一ID)”, UUID:“全局唯一ID UUID”
  mapper-locations: classpath:mapper/sms/**/*.xml
